from vidrovr.resources.metadata.asset_item import AssetItem, AssetItemModel
from vidrovr.resources.metadata.person import Person, PersonModel
from vidrovr.resources.metadata.custom_tags import CustomTag, CustomTagModel
from vidrovr.resources.metadata.generic_tags import GenericTag, GenericTagModel
from vidrovr.resources.metadata.iab_tags import IABTag, IABTagModel
from vidrovr.resources.metadata.keyphrases import Keyphrase, KeyphraseModel
from vidrovr.resources.metadata.named_entities import NamedEntities, NamedEntitiesModel
from vidrovr.resources.metadata.object import Object, ObjectModel
from vidrovr.resources.metadata.ocr import OCR, OCRModel
from vidrovr.resources.metadata.transcript import Transcript, TranscriptModel
