name: pull-request-lint-and-test
on:
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Lint using black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "./src/vidrovr"

      - name: Create Pull Request if Lint detects issues
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: ":zap: Linting ${{ env.SOURCE_BRANCH_NAME }}"
            commit-message: ":art: Linting ${{ env.SOURCE_BRANCH_NAME }}"
            body: |
                Fixing linting errors in ${{ github.sha }} by ${{ github.actor }}. 
            base: ${{ env.SOURCE_BRANCH_NAME }} # Creates pull request onto pull request or commit branch
            branch: actions/black/${{ env.SOURCE_BRANCH_NAME }}

      - name: Exit
        if: steps.action_black.outputs.is_formatted == 'true'
        run: exit 1
