name: release-to-pypi
on:
  release:
    types: ["published"]

jobs:
  release:
    name: release
    environment: PyPi Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
