name: release-to-pypi
on:
  release:
    types: ["published"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPi
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: PyPi Release
      url: https://pypi.org/p/vidrovr
    permissions:
      id-token: write
    steps:
      - name: Download dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
